### ISSUE TITLE
Make version repository optional

### ISSUE THREAD

**Issue by thesayyn** [bazel-contrib/bazel_features#32] opened 2023-12-26 02:54 UTC
Currently, there's an external repository with bazel version stamped inside .bzl file to allow access to bazel version from non-repository contexts. 

This is unnecessary if bazel_features is being called from a repository context where bazel-version is accessible therefore making the external version repository unnecessary.

**Comment by thesayyn** [comment] 2023-12-26 02:58
I guess bazel can make this easy on us and already expose bazel_version to BUILD context...

**Comment by Wyverald** [comment] 2024-01-17 22:31
The problem is that we can't `load` conditionally based on whether something is being accessed from a repo rule context or a build rule context (or something else, for that matter). So the extra repo will always be `load`ed from anyway.

Even if we made Bazel itself play nice, it's unlikely we could ever use the new feature and get rid of the extra repo since the whole spirit of `bazel_features` is to support multiple versions of Bazel.

I'll go ahead and close this, but as always we can reopen if necessary.

**Closed by Wyverald** 2024-01-17 22:31 UTC
